name: Site Screenshot
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 5
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://banami.nekoweb.org/bot.html
      - uses: actions/upload-artifact@v3
        with:
          name: hero-screenshot
          path: ${{ github.workspace }}/*.png
