name: Upload screenshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Sleep
        run: sleep 5
      
      - name: Take Screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://banami.nekoweb.org/bot.html
          output: hatterene.png
          
      - name: Prep
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add hatterene.png
          git commit -m "Screenshot"
      
      - name: Push
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

